sonar.projectKey=crm_vontamona
sonar.projectName=crm_vontamona

sonar.sourceEncoding=UTF-8

sonar.sources=server/src,client/components,client/lib
sonar.tests=server/src,server/test,client/components,client/lib

sonar.test.inclusions=server/src/**/*.spec.ts,server/test/**/*.e2e-spec.ts,client/**/*.{test,spec}.ts,client/**/*.{test,spec}.tsx

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/.next/**,**/*.d.ts,client/public/**,client/app/**

sonar.typescript.lcov.reportPaths=server/coverage/lcov.info,client/coverage/lcov.info
