---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
        - name: wait-for-backend
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until nc -z backend 3001; do echo waiting for backend; sleep 2; done;",
            ]
      containers:
        - name: frontend
          image: jenya00/crm_vontamona-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: INTERNAL_API_URL
              value: http://backend:3001
